POST実装&テスト&CI
CodeParty2021/code_party_runner pull request #1
Opened 2022-08-09 06:21 UTC by disk-12

最初のたたき台の実装

2022-08-09 06:55 UTC, disk-12 commented
**SwaggerUI用**
```
{
  "players": ["a","b","c","d"],
  "python_objects": ["def action(a,b):\n return 0","def action(a,b):\n return 0","def action(a,b):\n return 0","def action(a,b):\n return 0"],
  "json_dict": {}
}
```

2022-08-11 02:17 UTC, iikyara requested changes
何点かコメントしたので確認お願い！
基本的にはいい感じに動いてたと思う
ユーザコードの関数化だけ必須かなーって感じです

2022-08-11 02:17 UTC, iikyara commented on main.py
> +    )
`user_code`は文字列じゃなくて関数化して渡すのが正しそう
バックエンドだとこの部分
- [code_api/views.py#L31](https://github.com/CodeParty2021/code_party_back/blob/master/code_api/views.py#L31)


現状は、各プレーヤの出力にエラーが出てる感じ
```
...
"players": [
  {
    "x": 0,
    "y": 0,
    "state": 0,
    "action": 5,
    "score": 1,
    "print": "Traceback (most recent call last):\n  File \"/backend/game_libs/square_paint/./player.py\", line 20, in action\n    output = user_code(\nTypeError: 'str' object is not callable\n\n"
  },
  ...
]
...
```

ただ、これってバックエンドじゃなくてシミュレータ側でやるべき？
- チケット化して対応してもいいかもです

2022-08-11 02:17 UTC, iikyara commented on main_test.py
> +            "python_objects": python_objects,
テストは通るけど、ここも関数化した方がよさそう

2022-08-22 19:56 UTC, iikyara approved these changes
良い感じに動いてる！LGTM！

2022-08-24 12:10 UTC, merged